version: '3.8'

services:
  tams-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    volumes:
      - ./ml_models:/app/ml_models
    restart: unless-stopped
